name: ci-app
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make setup
      - name: test
        run: make test

  linter:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: make lint

