name: ci-app
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make setup
      - run: make startup

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make test

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make lint

